---

########################
# Change Variables here for EC2
########################

- name: Provision Test Ec2
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ec2_private_key: aws-patrick-oregon
    ec2_instance_type: t2.micro
    ec2_ami_image: ami-6df1e514
    ec2_subnet_id: subnet-9fcbd3c7
    ec2_region: us-west-2
    
  tasks:

########################
# Used for creating the EC2 Instance.
# Must not be deleted
########################

  - name: Create Test Ec2
    ec2:
      key_name: "{{ ec2_private_key }}"
      instance_type: "{{ ec2_instance_type }}"
      image: "{{ ec2_ami_image }}"
      wait: yes
      count: 1
      vpc_subnet_id: "{{ ec2_subnet_id }}"
      assign_public_ip: no
      region: "{{ ec2_region }}"
      instance_tags:
         ansible: jenkins
         buildcli: test
    register: ec2_instance

  - name: Temporary Add Host IP
    add_host:
      name: "{{ ec2_instance.instances[0].public_ip }}"
      groups: ec2-hosts
      instance_id: "{{ ec2_instance.instance_ids[0] }}"

########################
# Main Configuration Steps For New Instance

- name: Configuring new EC2 for Tests
  hosts: ec2-hosts
  user: ec2-user
  gather_facts: false
  tasks:

   - block:
       - name: Pause To bypass Connection Refused
         pause:
           seconds: 25

       - include: configure.yml

     rescue:
     # This is for access variables across hosts.
     # Sets a failure flag for when operators plays fail
       - debug: msg='Hit Rescue'

       - name: set Failure Fact
         command: echo "Failed"
         register: failed


########################
# Only executed when "-e delete_instance=true" or Failure flag is triggered in block

- name: Return EC2 Instance 
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - name: Delete Instance upon failure or specified
    ec2:
      state: absent
      instance_id: "{{ ec2_instance.instance_ids[0] }}"
      region: us-west-2
      wait: yes
    when: delete_instance | default("false") or hostvars[ec2_instance.instances[0].public_ip].failed.stdout is defined
    

