---

- name: Provision Test Ec2
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - name: Create Test Ec2
    ec2:
      key_name: aws-patrick-oregon
      instance_type: t2.micro
      image: ami-6df1e514
      wait: yes
      count: 1
      vpc_subnet_id: subnet-9fcbd3c7
      assign_public_ip: no
      region: us-west-2
      instance_tags:
         ansible: jenkins
         buildcli: test
    register: ec2_instance

  - name: Temporary Add Host IP
    add_host:
      name: "{{ ec2_instance.instances[0].public_ip }}"
      groups: ec2-hosts

- name: Test Ping New Host
  hosts: ec2-hosts
  user: ec2-user
  gather_facts: false
  tasks:

  - name: Pause To bypass Connection Refused
    pause:
      seconds: 25

  - name: "Say hello to my new Instance"
    ping: