---

# test.yml
- name: Bring up docker containers for docker connection inventory iface
  hosts: localhost
  roles:
    - role: provision_docker
      provision_docker_privileged: true,
      provision_docker_inventory_group: "{{ groups['containers'] }}"
      provision_docker_use_docker_connection: true

- hosts: containers
  tasks:
    - name: "Say hello to my new containers"
      ping: