---

- name: Provision Test Ec2
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - debug: msg="{{ansible_python_interpreter}}"

  - ec2:
      key_name: aws-patrick-oregon
      instance_type: t2.micro
      image: ami-6df1e514
      wait: yes
      count: 1
      vpc_subnet_id: subnet-9fcbd3c7
      assign_public_ip: no
      region: us-west-2
      instance_tags:
         ansible: jenkins
         buildcli: test
    register: ec2_instance

  - debug: var=ec2_instance

- hosts: "{{ ec2_instance.instances.public_ip }}"
  tasks:
  - name: "Say hello to my new containers"
    ping: