---

- name: Provision Test Ec2
  hosts: localhost
  gather_facts: false
  tasks:
  - debug: msg="{{ansible_python_interpreter}}"

  - ec2:
      key_name: aws-patrick-oregon
      instance_type: t2.micro
      image: ami-6df1e514
      wait: yes
      count: 1
      vpc_subnet_id: subnet-9fcbd3c7
      assign_public_ip: no

  - debug: var=ec2_instance

#- hosts: containers
#  tasks:
#    - name: "Say hello to my new containers"
#      ping: